module.exports = {
   blacklisted: [
      'phenom',
      'phenomanal',
      'phenomlol',
      'not phenom',
      'nigg',
      'nigger',
      'nigga',
      'negger',
      'nibba',
      'nigers',
      'nig3r',
      'n1gger',
      'niqqer',
      'fag',
      'faggit',
      'faggot',
      'porn',
      'pornhub',
      'bruhga',
      'bruhgga',
      'blackass',
      'zwosta',
   ],
};
