module.exports = {
   blacklisted: [
      'bruhga',
      'bruhgga',
      'blackass',
      'bill cosby',
      'bulgarski',
      'discord',
      'moderator',
      'staff',
      'fag',
      'faggit',
      'faggot',
      'fatban',
      'nigg',
      'negger',
      'nibb',
      'niger',
      'nig3er',
      'n1gger',
      'niqqer',
      'phenom',
      'porn',
      'p0rn',
      'pornhub',
      's3x',
      'tiffy',
      'rayyme',
      'zwosta',
   ],
};
